name: Node.js Lint & Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
#        node-version: [4.x, 6.x, 8.x, 10.x, 12.x, 14.x, 16.x, 18.x, 20.x]
        node-version: [4.x]
    steps:
      - uses: sergeysova/jq-action@v2
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # npm ci is not supported on node 4.x
      - run: npm install --production
      - run: npm install --save-dev mocha@5.2.0 ws@2.3.1 chai
      - run: npm run test:dist
